In [4]:
import pandas as pd
import numpy as np

In [5]:
labels = ["a","b","c"]
arr = np.array([10,20,30])
dict = {1:10,2:20,3:30}
MY_LIST = [10,20,30]

In [8]:
pd.Series(MY_LIST,index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

DATA_FRAMES

In [12]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

DATA FRAME USING THE LIST

In [21]:
df['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [23]:
df["profession"] = ["doctor","enginner","teacher","berozgaar"]
df

    Name  Age      City  Salary profession
0   John   28  New York   65000     doctor
1   Anna   34     Paris   70000   enginner
2  Peter   29    Berlin   62000    teacher
3  Linda   42    London   85000  berozgaar

In [36]:
df.drop("profession", axis = 1 , inplace= True)

KeyError: "['profession'] not found in axis"

In [41]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [42]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [50]:
df[(df['Age'] > 30) & (df['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000

FILLING THE MISSING VALUE AND REMOVE THE  MISSING VALUE HERE

In [6]:
import numpy as np
import pandas as pd



data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [8]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [9]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [14]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [16]:
values ={"A":10,"B":100,"C":50,"D":500}

df.fillna(value=values)

      A  B     C      D
0   1.0  1   1.0    1.0
1   2.0  2   2.0  500.0
2  10.0  3   3.0  500.0
3   4.0  4  50.0  500.0
4   5.0  5  50.0    5.0

In [17]:

df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

In [18]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [19]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [20]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [21]:
pd.merge(employees,salaries)

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [32]:

p1= pd.merge(employees, salaries, on='employee_id', how='outer')

In [33]:
p1

   employee_id   name department   salary    bonus
0            1   John         HR  60000.0   5000.0
1            2   Anna         IT  80000.0  10000.0
2            3  Peter    Finance  65000.0   7000.0
3            4  Linda         IT      NaN      NaN
4            5    Bob         HR      NaN      NaN
5            6    NaN        NaN  70000.0   8000.0
6            7    NaN        NaN  90000.0  12000.0

CONCATITON OF TWO DATAFRAME

In [35]:
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [36]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [38]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [39]:
pd.concat([df2,df1])

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [40]:
pd.concat([df2,df1],axis=1)

    A   B   C   A   B   C
0  A3  B3  C3  A0  B0  C0
1  A4  B4  C4  A1  B1  C1
2  A5  B5  C5  A2  B2  C2

In [41]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [43]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [47]:
cat = df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [48]:
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [49]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64

In [55]:
data = {
    'Date': pd.date_range('2023-01-01', periods=20),
    'Product': ['A', 'B', 'C', 'D'] * 5,
    'Region': ['East', 'West', 'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West',
               'North', 'South', 'East', 'West', 'North', 'South', 'East', 'West', 'North', 'South'],
    'Sales': np.random.randint(100, 1000, 20),
    'Units': np.random.randint(10, 100, 20),
    'Rep': ['John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary',
            'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice', 'John', 'Mary', 'Bob', 'Alice']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = 'Q' + df['Date'].dt.quarter.astype(str)
df

         Date Product Region  Sales  Units    Rep    Month Quarter
0  2023-01-01       A   East    338     47   John  January      Q1
1  2023-01-02       B   West    313     24   Mary  January      Q1
2  2023-01-03       C  North    963     72    Bob  January      Q1
3  2023-01-04       D  South    628     39  Alice  January      Q1
4  2023-01-05       A   East    953     77   John  January      Q1
5  2023-01-06       B   West    804     57   Mary  January      Q1
6  2023-01-07       C  North    713     22    Bob  January      Q1
7  2023-01-08       D  South    555     56  Alice  January      Q1
8  2023-01-09       A   East    218     91   John  January      Q1
9  2023-01-10       B   West    506     73   Mary  January      Q1
10 2023-01-11       C  North    647     77    Bob  January      Q1
11 2023-01-12       D  South    441     84  Alice  January      Q1
12 2023-01-13       A   East    890     21   John  January      Q1
13 2023-01-14       B   West    861     17   Mary  January      Q1
14 2023-01-15       C  North    603     14    Bob  January      Q1
15 2023-01-16       D  South    309     65  Alice  January      Q1
16 2023-01-17       A   East    103     91   John  January      Q1
17 2023-01-18       B   West    162     69   Mary  January      Q1
18 2023-01-19       C  North    553     66    Bob  January      Q1
19 2023-01-20       D  South    241     40  Alice  January      Q1

In [59]:
pivot2 = pd.pivot_table(df,values=["Sales"],index="Region",columns="Product")

pivot2

         Sales
Product      A      B      C      D
Region
East     500.4    NaN    NaN    NaN
North      NaN    NaN  695.8    NaN
South      NaN    NaN    NaN  434.8
West       NaN  529.2    NaN    NaN

In [60]:
pd.crosstab(df['Region'],df['Product'])

Product  A  B  C  D
Region
East     5  0  0  0
North    0  0  5  0
South    0  0  0  5
West     0  5  0  0

In [62]:
df1 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5],
    'B': [10, 20, 30, 40, 50],
    'C': [100, 200, 300, 400, 500]
})
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [63]:
df1.shape

(5, 3)

In [64]:
df1.info

<bound method DataFrame.info of    A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500>

In [65]:
df1.columns

Index(['A', 'B', 'C'], dtype='str')

In [66]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

In [67]:
df1.describe()

              A          B           C
count  5.000000   5.000000    5.000000
mean   3.000000  30.000000  300.000000
std    1.581139  15.811388  158.113883
min    1.000000  10.000000  100.000000
25%    2.000000  20.000000  200.000000
50%    3.000000  30.000000  300.000000
75%    4.000000  40.000000  400.000000
max    5.000000  50.000000  500.000000

In [69]:
df1

   A   B    C
0  1  10  100
1  2  20  200
2  3  30  300
3  4  40  400
4  5  50  500

In [72]:
df1["C"] + 10

0    110
1    210
2    310
3    410
4    510
Name: C, dtype: int64

In [73]:
df1['D'] = df1["B"].apply(lambda x : x**2)

In [74]:
df1

   A   B    C     D
0  1  10  100   100
1  2  20  200   400
2  3  30  300   900
3  4  40  400  1600
4  5  50  500  2500