In [4]:
import pandas as pd
import numpy as np

In [5]:
labels = ["a","b","c"]
arr = np.array([10,20,30])
dict = {1:10,2:20,3:30}
MY_LIST = [10,20,30]

In [8]:
pd.Series(MY_LIST,index=labels)

a    10
b    20
c    30
dtype: int64

In [10]:
pd.Series(dict)

1    10
2    20
3    30
dtype: int64

DATA_FRAMES

In [12]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}

df = pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

DATA FRAME USING THE LIST

In [21]:
df['City']

0    New York
1       Paris
2      Berlin
3      London
Name: City, dtype: str

In [23]:
df["profession"] = ["doctor","enginner","teacher","berozgaar"]
df

    Name  Age      City  Salary profession
0   John   28  New York   65000     doctor
1   Anna   34     Paris   70000   enginner
2  Peter   29    Berlin   62000    teacher
3  Linda   42    London   85000  berozgaar

In [36]:
df.drop("profession", axis = 1 , inplace= True)

KeyError: "['profession'] not found in axis"

In [41]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [42]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

In [50]:
df[(df['Age'] > 30) & (df['City'] == 'Paris')]

   Name  Age   City  Salary
1  Anna   34  Paris   70000